server:
  port: 8080
  servlet:
    context-path: /api/v1
  error:
    include-message: always
spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yml
    password: 551617
    user: admin
    url: jdbc:postgresql://127.0.0.1:5432/mt
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
  datasource:
    username: admin
    password: 551617
    url: jdbc:postgresql://127.0.0.1:5432/mt
    driver-class-name: org.postgresql.Driver
